"""
Project Model Exporters

Exports ProjectModel + combined summary to:
  - project_model.json
  - summary.md
"""
import json
from typing import Optional

from state import ProjectModel, ArchitectureModel, DatabaseModel, OpenAPIModel


def export_project_model_json(project_model: ProjectModel) -> str:
    """Serialize the ProjectModel as formatted JSON."""
    return json.dumps(project_model.model_dump(), indent=2, ensure_ascii=False) + "\n"


def export_summary_markdown(
    project_model: Optional[ProjectModel],
    architecture_model: Optional[ArchitectureModel],
    database_model: Optional[DatabaseModel],
    openapi_model: Optional[OpenAPIModel],
) -> str:
    """
    Generate a human-readable Markdown project summary combining all models.

    Sections:
      - Project Overview (CPM)
      - Architecture Summary
      - Database Summary
      - API Summary
    """
    lines: list[str] = []

    # ─── Header ──────────────────────────────────────────────────────────────
    lines += [
        "# Archon System Design Summary",
        "",
        "> Generated by Archon AI Design Platform — deterministic export.",
        "",
        "---",
        "",
    ]

    # ─── Project Overview ────────────────────────────────────────────────────
    lines += ["## Project Overview", ""]

    if project_model:
        if project_model.actors:
            lines += ["### Actors", ""]
            for actor in project_model.actors:
                lines.append(f"- {actor}")
            lines.append("")

        if project_model.features:
            lines += ["### Key Features", ""]
            for feat in project_model.features:
                lines.append(f"- {feat}")
            lines.append("")

        if project_model.user_stories:
            lines += ["### User Stories", ""]
            for story in project_model.user_stories:
                lines.append(f"- {story}")
            lines.append("")

        if project_model.functional_requirements:
            lines += ["### Functional Requirements", ""]
            for req in project_model.functional_requirements:
                lines.append(f"- {req}")
            lines.append("")

        if project_model.non_functional_requirements:
            lines += ["### Non-Functional Requirements", ""]
            for req in project_model.non_functional_requirements:
                lines.append(f"- {req}")
            lines.append("")

        if project_model.constraints:
            lines += ["### Constraints", ""]
            for c in project_model.constraints:
                lines.append(f"- {c}")
            lines.append("")

        if project_model.assumptions:
            lines += ["### Assumptions", ""]
            for a in project_model.assumptions:
                lines.append(f"- {a}")
            lines.append("")
    else:
        lines += ["_Project model not available._", ""]

    lines += ["---", ""]

    # ─── Architecture Summary ─────────────────────────────────────────────────
    lines += ["## Architecture Summary", ""]

    if architecture_model:
        lines.append(f"**Pattern:** {architecture_model.architecture_pattern}")
        lines.append("")

        if architecture_model.services:
            lines += ["### Services", ""]
            for svc in architecture_model.services:
                lines.append(f"#### {svc.name}")
                if svc.responsibilities:
                    for r in svc.responsibilities:
                        lines.append(f"- {r}")
                if svc.technology_stack:
                    tech = ", ".join(svc.technology_stack)
                    lines.append(f"- **Stack:** {tech}")
                lines.append("")

        if architecture_model.datastores:
            lines += ["### Datastores", ""]
            for ds in architecture_model.datastores:
                lines.append(f"| {ds.name} | {ds.type} | {ds.technology} | {ds.justification} |")
            lines = lines[:-len(architecture_model.datastores)]
            lines.append("| Name | Type | Technology | Justification |")
            lines.append("|------|------|-----------|---------------|")
            for ds in architecture_model.datastores:
                lines.append(f"| {ds.name} | {ds.type} | {ds.technology} | {ds.justification} |")
            lines.append("")

        if architecture_model.external_integrations:
            lines += ["### External Integrations", ""]
            for intg in architecture_model.external_integrations:
                lines.append(f"- **{intg.name}** ({intg.type}) — {intg.protocol_api}")
            lines.append("")

        if architecture_model.queues:
            lines += ["### Message Queues", ""]
            for q in architecture_model.queues:
                lines.append(f"- **{q.name}**: {q.producer} → {q.consumer} — {q.purpose}")
            lines.append("")

        sec = architecture_model.security
        lines += [
            "### Security",
            "",
            f"- **Authentication:** {sec.authentication}",
            f"- **Authorization:** {sec.authorization}",
        ]
        if sec.data_protection:
            for dp in sec.data_protection:
                lines.append(f"- **Data Protection:** {dp}")
        lines.append("")

        scal = architecture_model.scalability
        lines += [
            "### Scalability",
            "",
            f"- **Scaling Strategy:** {scal.scaling_strategy}",
            f"- **Caching:** {scal.caching_strategy}",
        ]
        if scal.bottlenecks:
            for b in scal.bottlenecks:
                lines.append(f"- **Bottleneck:** {b}")
        lines.append("")
    else:
        lines += ["_Architecture model not available._", ""]

    lines += ["---", ""]

    # ─── Database Summary ─────────────────────────────────────────────────────
    lines += ["## Database Summary", ""]

    if database_model:
        lines += [f"**Tables:** {len(database_model.tables)}", ""]

        for table in database_model.tables:
            lines.append(f"### `{table.name}`")
            if table.description:
                lines.append(f"_{table.description}_")
            lines.append("")
            lines.append("| Column | Type | PK | Nullable | Unique |")
            lines.append("|--------|------|----|---------:|-------:|")
            for col in table.columns:
                pk  = "✓" if col.primary_key else ""
                nn  = "✓" if col.nullable else "✗"
                unq = "✓" if col.unique else ""
                lines.append(f"| {col.name} | {col.type} | {pk} | {nn} | {unq} |")
            lines.append("")

        if database_model.relationships:
            lines += ["### Relationships", ""]
            for rel in database_model.relationships:
                lines.append(f"- `{rel.source_table}` **{rel.relationship_type.value}** `{rel.target_table}` — {rel.description}")
            lines.append("")

        if database_model.indexes:
            lines += ["### Indexes", ""]
            for idx in database_model.indexes:
                cols = ", ".join(idx.columns)
                lines.append(f"- `{idx.table}` ({cols}) — {idx.reason}")
            lines.append("")
    else:
        lines += ["_Database model not available._", ""]

    lines += ["---", ""]

    # ─── API Summary ──────────────────────────────────────────────────────────
    lines += ["## API Summary", ""]

    if openapi_model:
        lines += [f"**Endpoints:** {len(openapi_model.endpoints)}", ""]
        lines.append("| Method | Path | Service | Auth | Summary |")
        lines.append("|--------|------|---------|:----:|---------|")
        for ep in sorted(openapi_model.endpoints, key=lambda e: (e.service, e.path, e.method)):
            auth = "🔒" if ep.authentication_required else "🔓"
            lines.append(f"| `{ep.method.upper()}` | `{ep.path}` | {ep.service} | {auth} | {ep.summary} |")
        lines.append("")
    else:
        lines += ["_API model not available._", ""]

    return "\n".join(lines)
